### PR TITLE
feat: Add log_analytics_workspace_daily_quota_gb variable

### LINKED ISSUE #1: [FEAT] Allow custom daily_quota_gb for azurerm_log_analytics_workspace
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, users of the logs submodule can only specify [retention_in_days](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace#retention_in_days):

https://github.com/claranet/terraform-azurerm-run/blob/d0a98ab25a7f46853f0fb369b8902fec94ee9d64/modules/logs/r-logs.tf#L10-L11

It would be very useful if value of [daily_quota_gb](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace#daily_quota_gb) can also be adjusted.

### New or Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Potential Terraform Configuration

Addition of new variable

```hcl
variable "log_analytics_workspace_daily_quota_gb" {
  description = "The workspace daily quota for ingestion in GB. Defaults to -1 (unlimited)."
  type        = number
  default     = -1
}
```

will allow refined configuration like in this example:

```hcl
module "logs" {
  source  = "claranet/run/azurerm//modules/logs"
  version = "x.x.x"

  client_name    = var.client_name
  location       = module.azure_region.location
  location_short = module.azure_region.location_short
  environment    = var.environment
  stack          = var.stack

  resource_group_name = module.rg.resource_group_name

  log_analytics_workspace_sku               = "PerGB2018"
  log_analytics_workspace_retention_in_days = 30  # Minimum for PerGB2018
  log_analytics_workspace_daily_quota_gb    = 0.5 # Based on legacy Free SKU default daily quota

  extra_tags = {
    foo = "bar"
  }
}
```

### References

_No response_

### PR DESCRIPTION
**Pull request by mloskot**
Enables the logs module users to adjust `daily_quota_gb`
property of `azurerm_log_analytics_workspace` resource.

Closes #1

### CODE REVIEW

**Review by BzSpi — APPROVED** [review]

**Comment by mloskot** [comment]
The failing lint CI is unrelated to the change in this PR

```
Warning: [Fixable] Lookup with 2 arguments is deprecated (terraform_deprecated_lookup)

  on locals-tags.tf line 11:
  11:     for key in try(chunklist(keys(local.merged_tags), 14)[0], []) : key => lookup(local.merged_tags, key)

Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_lookup.md

Warning: [Fixable] Lookup with 2 arguments is deprecated (terraform_deprecated_lookup)

  on locals-tags.tf line 17:
  17:     try({ "extra_tags" = jsonencode({ for key in slice(keys(local.merged_tags), 14, length(local.merged_tags)) : key => lookup(local.merged_tags, key) }) }, {})
```

It looks like ` lookup(local.merged_tags, key)` needs to be simplified to `local.merged_tags[key]`.

**Comment by Shr3ps** [comment]
> The failing lint CI is unrelated to the change in this PR
> 
> ```
> Warning: [Fixable] Lookup with 2 arguments is deprecated (terraform_deprecated_lookup)
> 
>   on locals-tags.tf line 11:
>   11:     for key in try(chunklist(keys(local.merged_tags), 14)[0], []) : key => lookup(local.merged_tags, key)
> 
> Reference: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_lookup.md
> 
> Warning: [Fixable] Lookup with 2 arguments is deprecated (terraform_deprecated_lookup)
> 
>   on locals-tags.tf line 17:
>   17:     try({ "extra_tags" = jsonencode({ for key in slice(keys(local.merged_tags), 14, length(local.merged_tags)) : key => lookup(local.merged_tags, key) }) }, {})
> ```
> 
> It looks like ` lookup(local.merged_tags, key)` needs to be simplified to `local.merged_tags[key]`.

can you fix this too in this PR?

**Comment by mloskot** [comment]
@Shr3ps  Sure, done.

**Comment by mloskot** [comment]
Hmm, does the CI/TFDocs failure mean I should remove the changes to the `README.md`?

**Comment by Shr3ps** [comment]
> Hmm, does the CI/TFDocs failure mean I should remove the changes to the `README.md`?

The README should be generated by `pre-commit`, it seems you didn't use it, the CI fails because alphabetic sort/order of variables is not respected.

**Comment by mloskot** [comment]
> The README should be generated by pre-commit

Oh, right! I will set it up locally and update my PR over the weekend.

**Comment by mloskot** [comment]
@Shr3ps 
> The README should be generated by pre-commit

I've just installed pre-commit hooks and it's done its job fine, I believe, updating my changes.

**Review by Shr3ps — APPROVED** [review]

**Pull request merged**
